import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";
import zlib from "zlib";

const prod = (process.argv[2] === "production");

const CEDICT_TXT = "cedict_1_0_ts_utf-8_mdbg_20240705_025126.txt";

// Assemble a self-contained `dist/` that can be dropped into a vault's
// .obsidian/plugins/hanzi-practice/ for a real install: the bundled main.js,
// the manifest, and the CEDICT dictionary GZIPPED (the raw file is ~10MB; gzip
// takes it to ~3MB). The plugin inflates it at runtime (see cedict_parser.ts).
function emitDist() {
	const distDir = path.join(process.cwd(), "dist");
	fs.mkdirSync(distDir, { recursive: true });
	fs.copyFileSync("main.js", path.join(distDir, "main.js"));
	fs.copyFileSync("manifest.json", path.join(distDir, "manifest.json"));
	const raw = fs.readFileSync(CEDICT_TXT);
	const gz = zlib.gzipSync(raw, { level: zlib.constants.Z_BEST_COMPRESSION });
	fs.writeFileSync(path.join(distDir, `${CEDICT_TXT}.gz`), gz);
	console.log(`dist/: main.js, manifest.json, ${CEDICT_TXT}.gz ` +
		`(${(raw.length / 1e6).toFixed(1)}MB -> ${(gz.length / 1e6).toFixed(1)}MB gz)`);
}

const context = await esbuild.context({
	banner: {
		js: '/*\nTHIS IS A GENERATED/BUNDLED FILE BY ESBUILD\n*/',
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2022",
	tsconfig: "tsconfig.json",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	emitDist();
	await context.dispose(); // stop the esbuild service cleanly (avoids a shutdown deadlock)
	process.exit(0);
} else {
	await context.watch();
}
