import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";
import zlib from "zlib";
import cp from "child_process";

const prod = (process.argv[2] === "production");

const CEDICT_TXT = "cedict_1_0_ts_utf-8_mdbg_20240705_025126.txt";
const STROKES_GZ = "hanzi-strokes.bin.gz";

// Generate the medians-only stroke database (dist/hanzi-strokes.bin.gz) from
// the hanzi-writer-data devDependency. The generator is TypeScript (it shares
// the HZS1 codec with the runtime reader), so bundle it for node first, then
// run it as a child process.
async function genStrokeData(distDir) {
	const genDir = path.join(process.cwd(), "node_modules", ".cache", "hanzi-gen");
	const genOut = path.join(genDir, "gen_stroke_data.cjs");
	await esbuild.build({
		entryPoints: ["scripts/gen_stroke_data.ts"],
		bundle: true,
		platform: "node",
		format: "cjs",
		target: "node18",
		outfile: genOut,
		logLevel: "silent",
	});
	const dataDir = path.join(process.cwd(), "node_modules", "hanzi-writer-data");
	cp.execFileSync(process.execPath, [genOut, dataDir, path.join(distDir, STROKES_GZ)], {
		stdio: "inherit",
	});
}

// Assemble a self-contained `dist/` that can be dropped into a vault's
// .obsidian/plugins/hanzi-practice/ for a real install: the bundled main.js,
// the manifest, and the CEDICT dictionary GZIPPED (the raw file is ~10MB; gzip
// takes it to ~3MB). The plugin inflates it at runtime (see cedict_parser.ts).
// Also packs everything into dist/hanzi-practice-<version>.tar.gz — the single
// release asset the BRAT fork downloads and extracts (it requires main.js +
// manifest.json at the archive root and installs every file it contains).
async function emitDist() {
	const distDir = path.join(process.cwd(), "dist");
	fs.mkdirSync(distDir, { recursive: true });
	fs.copyFileSync("main.js", path.join(distDir, "main.js"));
	fs.copyFileSync("manifest.json", path.join(distDir, "manifest.json"));
	const raw = fs.readFileSync(CEDICT_TXT);
	const gz = zlib.gzipSync(raw, { level: zlib.constants.Z_BEST_COMPRESSION });
	fs.writeFileSync(path.join(distDir, `${CEDICT_TXT}.gz`), gz);
	await genStrokeData(distDir);
	const tarball = emitTarball(distDir);
	console.log(`dist/: main.js, manifest.json, ${STROKES_GZ}, ${CEDICT_TXT}.gz ` +
		`(${(raw.length / 1e6).toFixed(1)}MB -> ${(gz.length / 1e6).toFixed(1)}MB gz), ${tarball}`);
}

function emitTarball(distDir) {
	const manifest = JSON.parse(fs.readFileSync("manifest.json", "utf8"));
	const tarball = `${manifest.id}-${manifest.version}.tar.gz`;
	// drop tarballs from previous versions so dist/ only ever has the current one
	for (const old of fs.readdirSync(distDir).filter((f) => f.endsWith(".tar.gz"))) {
		fs.rmSync(path.join(distDir, old));
	}
	const files = ["main.js", "manifest.json", `${CEDICT_TXT}.gz`, STROKES_GZ];
	cp.execFileSync("tar", [
		"-czf", path.join(distDir, tarball),
		"--owner=0", "--group=0", "--numeric-owner", "--sort=name",
		"-C", distDir, ...files,
	]);
	return tarball;
}

const context = await esbuild.context({
	banner: {
		js: '/*\nTHIS IS A GENERATED/BUNDLED FILE BY ESBUILD\n*/',
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2022",
	tsconfig: "tsconfig.json",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	await emitDist();
	await context.dispose(); // stop the esbuild service cleanly (avoids a shutdown deadlock)
	process.exit(0);
} else {
	await context.watch();
}
